[build-system]
requires = ["setuptools>=58.0.3", "wheel>=0.37.0"]

[tool.poetry]
name = "get_patchlib"
version = "1.0"
description = "Patch file handler"
authors = [{ name = "BretteFromNesUniverse"}]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.7"